### ISSUE TITLE
How to define smart constructors?

### ISSUE THREAD

**Issue by toraritte** [expede/algae#37]
Is this as trivial as [overwriting the `new` constructor](https://hexdocs.pm/algae/readme.html#overwrite-constructor) using `defp` instead of `def` and call `new` from the module's functions?

**Comment by toraritte** [comment]
No.

```elixir
iex(23)> defmodule C do                             
...(23)>   import Algae                               
...(23)>     defdata do                                 
...(23)>       a :: String.t()                            
...(23)>       b :: non_neg_integer()                     
...(23)>     end
...(23)> 
...(23)>     defp new(a,b), do: %B{a: a, b: b}
...(23)> 
...(23)>     def make_new(a,b), do: new(a,b)
...(23)> end
{:module, C,
 <<70, 79, 82, 49, 0, 0, 7, 192, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 204,
   0, 0, 0, 23, 8, 69, 108, 105, 120, 105, 114, 46, 67, 8, 95, 95, 105, 110,
   102, 111, 95, 95, 7, 99, 111, 109, 112, ...>>, {:make_new, 2}}
iex(24)> C.new 
%B{a: "", b: 0}
iex(25)> C.make_new
** (UndefinedFunctionError) function C.make_new/0 is undefined or private. Did you mean one of:

      * make_new/2

    C.make_new()
```

**Comment by OvermindDL1** [comment]
Elixir doesn't have partial application so your `def make_new(a,b), do: new(a,b)` then running `C.make_new` will always fail unless something defines a `make_new/0`, which nothing it in that example.  That specific error is a normal elixir error, not an algae error.

**Comment by toraritte** [comment]
Wow, I'm an idiot, just looked at it again... Thanks

**Comment by OvermindDL1** [comment]
Happens to us all, very much.  ^.^;

**Comment by toraritte** [comment]
https://github.com/toraritte/algae/commit/03059078b96ddadf167ec541fef06d823a99bfa3

```elixir
defmodule Int do
  import Algae

  defdata do
    int :: integer()
  end

  def new() do
    super()
    raise(UndefinedFunctionError, "Int.new/0 is undefined or private")
  end

  def new(int) when is_integer(int) do
    super(int)
  end

  def new(_), do: raise(ArgumentError, "not int")
end
```

```text
iex(2)> Int.new
** (UndefinedFunctionError) undefined function
    iex:10: Int.new/0
iex(2)> Int.new(:a)
** (ArgumentError) not int
    iex:17: Int.new/1
iex(2)> Int.new(2)
%Int{int: 2}
```

**Comment by toraritte** [comment]
Went a bit further and tried to achieve this (works the same both in PureScript and Haskell):

```purescript
> data Cake = Cake Int String
> :type Cake
Int -> String -> Cake

> :type (Cake 27)
String -> Cake

> miez = Cake 27
> :type miez "lofa"
Cake
```

Algae types so far return default values when invoked with less arguments then needed but I like the above way of returning a constructor.

https://github.com/toraritte/algae/commit/084ab73e2253624aa35f231b584e51500f16fdee

```elixir
defmodule Int do
  import Algae

  defdata do
    int :: integer()
  end

  # def new() do
  #   super()
  #   raise(UndefinedFunctionError, "Int.new/0 is undefined or private")
  # end

  def new(int) when is_integer(int) do
    super(int)
  end

  def new(_), do: raise(ArgumentError, "not int")
end
```

```text
iex(3)> Int.new
#Function<1.87469375/1 in Int.new/0>
iex(4)> Int.new.(27)
%Int{int: 27}
iex(5)> Int.new.(:a)
** (ArgumentError) not int
    iex:17: Int.new/1
```

**Comment by toraritte** [comment]
https://github.com/toraritte/algae/commit/6d19fe1484fb5592fab5d2cf48b972e250e84280

Ugly, dirty, naive, etc., but just trying to prove a
concept.  The idea  would  be  that primitive  types
call  functions named  after  them  that will  check
types  using guards,  and  return  the given  value,
`raise`  otherwise. Currently  nothing is  done with
the  returned value,  because  if  all given  values
typecheck, the struct can  be built without them. So
maybe just raising would be enough.

Couldn't   put   `Algae.Prim.integer`   instead   of
just   `integer`    (same   goes    for   `string`),
because    something    doesn't     like    it    in
`Algae.Internal.module_elements/2`     (called    in
`Algae.Internal.data_ast(lines, ...)`).  Maybe there
is  no  need  to  bother,  because  these  would  be
primitive types.

The idea is that there  are primitive types that can
be  typechecked with  Elixir/Erlang guards,  and the
rest should  be defined  via Algae. Algae  types are
structs, so just checking  whether the module exists
should  be enough.  Unless I  am oversimplifying  it
again.

```elixir
defmodule Person do
  import Algae
  defdata do
    name :: string
    age  :: integer
  end
end
```

```text
{:module, Person,
 <<70, 79, 82, 49, 0, 0, 9, 164, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 1, 35,
   0, 0, 0, 30, 13, 69, 108, 105, 120, 105, 114, 46, 80, 101, 114, 115, 111,
   110, 8, 95, 95, 105, 110, 102, 111, 95, 95, ...>>, :ok}

iex(2)> Person.new("lofa", 27)
%Person{age: 27, name: "lofa"}

iex(3)> Person.new("lofa", :a)
** (ArgumentError) not integer
    (algae) lib/algae/prim.ex:3: Algae.Prim.integer/1
    iex:3: anonymous fn/2 in Person.new/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/2

iex(3)> Person.new(2, 27)
** (ArgumentError) not string
    (algae) lib/algae/prim.ex:6: Algae.Prim.string/1
    iex:3: anonymous fn/2 in Person.new/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/2
```
--------

**note**: Even though data constructors are curried now, this is still not pretty with the above commit:

```purescript
data D = D String Int
halfData = D "lofa"
-- works
halfData2 = D 27
-- crash
```

```text
iex(3)> Person.new
#Function<1.1752530/1 in Person.new/0>

iex(4)> Person.new.(27)   
#Function<2.1752530/1 in Person.new/1>

iex(5)> Person.new.(27).(2)
** (ArgumentError) not string
    (algae) lib/algae/prim.ex:6: Algae.Prim.string/1
    iex:3: anonymous fn/2 in Person.new/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/2
```

But with `defpartialx`, the data constructor clauses can be overridden, so that could be done for each clause. There is a catch though: as of this moment, each subsequent clause would have to add the previous check with their current curried argument (see below). I'm sure I am overlooking something something obvious.

  ```elixir
  defmodule D do

    defmacro __using__(_) do
      quote do
        use Quark

        defpartialx m(a,b,c), do: a-b-c

        defoverridable [m: 0, m: 1, m: 2, m: 3]

        # immediately overriding what is needed
        def m(i) when is_integer(i), do: super(i)
        def m(_), do: raise(ArgumentError, "not int")

        def m(i, j) when is_integer(i) and is_integer(j), do: super(i,j)
        def m(_,_), do: raise(ArgumentError, "not int")
      end
    end
  end

  defmodule E do
    use D

    def m(a) when is_integer(a), do: super(a)
    def m(_), do: raise(ArgumentError, "not int")

    def m(a,b) when is_integer(a) and is_integer(b), do: super(a,b)
    def m(_,_), do: raise(ArgumentError, "not int")

    def m(a,b,c) when is_integer(a) and is_integer(b) and is_integer(c), do: super(a,b,c)
    def m(_,_,_), do: raise(ArgumentError, "not int")
  end
  ```
(The overridden module bodies would call their typecheck functions instead of guards though, and then `super` if nothing is raised.)

**Comment by toraritte** [comment]
https://github.com/toraritte/algae/commit/723d6f16985c12516f33727aca3d583802237231

Overriding data constructors right after creation in `defdatax/2` (i.e., `Algae.Internal.data_astx/2`). To achieve it manually:

```elixir
defmodule Person do
  import Algae
  defdatax do
    name :: string
    age  :: integer
  end

   def new(str) do
     apply(Algae.Prim, :string, [str])
     super(str)
   end

   def new(str, int) do
     apply(Algae.Prim, :string, [str])
     apply(Algae.Prim, :integer, [int])
     super(str, int)
   end
end
```
----
Testing:
```elixir
defmodule Person do
  import Algae
  defdatax do
    name :: string
    age  :: integer
  end
end
```
```text
iex(2)> Person.new.(27)
** (ArgumentError) not string
    (algae) lib/algae/prim.ex:6: Algae.Prim.string/1
    iex:3: anonymous fn/2 in Person.new/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/1

iex(3)> Person.new.("lofa").(27)
["lofa", 27]
%Person{age: 27, name: "lofa"}

iex(4)> Person.new.("lofa").(:a)
** (ArgumentError) not integer
    (algae) lib/algae/prim.ex:3: Algae.Prim.integer/1
    iex:3: anonymous fn/2 in Person.new/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/2

iex(4)> Person.new.(9).(27)     
** (ArgumentError) not string
    (algae) lib/algae/prim.ex:6: Algae.Prim.string/1
    iex:3: anonymous fn/2 in Person.new/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/1

iex(4)> Person.new.(9).(:a)
** (ArgumentError) not string
    (algae) lib/algae/prim.ex:6: Algae.Prim.string/1
    iex:3: anonymous fn/2 in Person.new/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/1

iex(2)> Person.new(27)
** (ArgumentError) not string
    (algae) lib/algae/prim.ex:6: Algae.Prim.string/1
    iex:3: anonymous fn/2 in Person.new/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/1

iex(4)> Person.new("lofa").(27) 
["lofa", 27]
%Person{age: 27, name: "lofa"}

iex(5)> Person.new(7).(27)     
** (ArgumentError) not string
    (algae) lib/algae/prim.ex:6: Algae.Prim.string/1
    iex:3: anonymous fn/2 in Person.new/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/1

iex(5)> Person.new("lofa").(:a)
** (ArgumentError) not integer
    (algae) lib/algae/prim.ex:3: Algae.Prim.integer/1
    iex:3: anonymous fn/2 in Person.new/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/2

iex(2)> Person.new("lofa", 27)
["lofa", 27]
%Person{age: 27, name: "lofa"}

iex(3)> Person.new("lofa", :a)
** (ArgumentError) not integer
    (algae) lib/algae/prim.ex:3: Algae.Prim.integer/1
    iex:3: anonymous fn/2 in Person.new/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/2

iex(3)> Person.new(2, 27)     
** (ArgumentError) not string
    (algae) lib/algae/prim.ex:6: Algae.Prim.string/1
    iex:3: anonymous fn/2 in Person.new/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/2
```

**Comment by toraritte** [comment]
https://github.com/toraritte/algae/commit/a87c8b561806b8bd7642627cd0656caee109c090

Adding type checking for Algae types by defining a `type/1` function. Could've added just an extra field to Algae types, but didn't want to pollute the structs with extra keys. `type/1` is overridable to make it more flexible for other use cases. Currently it just takes the input Algae type, extracts its arguments in the right order and calls new with them. For example is some passes a struct that is not created with the `new` constructors, it will make sure that the right types match, or raise otherwise.

```elixir
defmodule Person do
  import Algae
  defdatax do
    name :: string
    age  :: integer
  end

  # def new(str) do
  #   apply(Algae.Prim, :string, [str])
  #   super(str)
  # end

  # def new(str, int) do
  #   apply(Algae.Prim, :string, [str])
  #   apply(Algae.Prim, :integer, [int])
  #   super(str, int)
  # end
end

defmodule Employee do
  import Algae
  defdatax do
    person :: Person
    role :: string
  end
end
```
```text
iex(4)> p = Person.new("lofa", 27); Employee.new.(p).("miez")      
%Employee{person: %Person{age: 27, name: "lofa"}, role: "miez"}

iex(5)> Employee.new.(%Person{age: :a, name: "lofa"}).("miez")
** (ArgumentError) not integer
    (algae) lib/algae/prim.ex:3: Algae.Prim.integer/1
    iex:3: anonymous fn/2 in Person.new/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:3: Person.new/2
    iex:5: anonymous fn/2 in Employee.new/1
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    iex:5: Employee.new/1
```
